querydb:
    image: mongo:3.4.4
    container_name: "query"

cube:
  build: .
  env_file: .env
  expose:
    - "4000"
  ports:
    - "4000:4000"
  volumes:
    - ./VizRec/query/schema
  command: node index.js
  links:
    - querydb
